Yiim.Web/Controllers/ConsoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Yiim.Interfaces;

namespace Yiim.Web.Controllers
{
    public class ConsoleController : _BaseController
    {
        //
        // GET: /Console/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult UnLogin()
        {
            return Redirect("Login");
        }
    }
}

Yiim.Web/Controllers/FunctionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Yiim.Interfaces;
using Yiim.ViewModels;

namespace Yiim.Web.Controllers
{
    public class FunctionsController : ApiController
    {
        public IFunctionality Service { get; set; }
        public FunctionsController(IFunctionality service)
        {
            this.Service = service;
        }
        [AcceptVerbs("GET")]
        public ResultBase Gets([FromUri]PageParams param)
        {
            return Service.Get(param);
        }
        [AcceptVerbs("PUT")]
        public ResultBase Put([FromBody]IdWithName model)
        {
            return Service.Put(model);
        }
        [AcceptVerbs("POST")]
        public ResultBase Post([FromBody]IdWithName model)
        {
            return Service.Post(model);
        }
        [AcceptVerbs("DELETE")]
        public ResultBase Delete(int id)
        {
            return Service.Delete(id);
        }
    }
}

Yiim.Web/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Yiim.Interfaces;
using Yiim.ViewModels;

namespace Yiim.Web.Controllers
{
    public class RolesController : ApiController
    {
        public IRoles Service { get; set; }
        public RolesController(IRoles service)
        {
            Service = service;
        }
        [AcceptVerbs("GET")]
        public ResultBase Gets([FromUri]RoleParams param)
        {
            return Service.Gets(param);
        }
        [AcceptVerbs("Post")]
        public ResultBase Post([FromBody] RoleDetails model)
        {
            return Service.Post(model);
        }
        [AcceptVerbs("PUT")]
        public ResultBase Put([FromBody] RoleDetails model)
        {
            return Service.Put(model);
        }
        [AcceptVerbs("DELETE")]
        public ResultBase Delete(int id)
        {
            return Service.Delete(id);
        }
    }
}

Yiim.Web/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Yiim.Interfaces;
using Yiim.ViewModels;

namespace Yiim.Web.Controllers
{
    public class UsersController : ApiController
    {
        public IUsers Service { get; set; }
        public UsersController(IUsers service)
        {
            Service = service;
        }
        [AcceptVerbs("GET")]
        public ResultBase Gets([FromUri]PageParams param)
        {
            return Service.Gets(param);
        }
        [AcceptVerbs("GET")]
        public ResultBase Get(int id)
        {
            return Service.Get(id);
        }
        [AcceptVerbs("POST")]
        public ResultBase Post(UserDetails user)
        {
            return Service.Post(user);
        }
        [AcceptVerbs("PUT")]
        public ResultBase Put(UserDetails user)
        {
            return Service.Put(user);
        }
        [AcceptVerbs("DELETE")]
        public ResultBase Delete(int id)
        {
            return Service.Delete(id);
        }
        [AcceptVerbs("PUT")]
        public ResultBase PutRoles([FromBody]UserDetails model)
        {
            return Service.PutRoles(model);
        }
        [AcceptVerbs("DELETE")]
        public ResultBase DeleteRole(int id, int roleId)
        {
            return Service.DeleteRole(id, roleId);
        }
    }
}

Yiim.Web/Controllers/UtilsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Yiim.Web.Controllers
{
    public class UtilsController : Controller
    {
        public ActionResult Html(string dir, string name)
        {
            string html = string.Format("~/App/views/{0}/{1}.html", dir, name);
            if (!System.IO.File.Exists(Server.MapPath(html)))
                return Content(string.Format("当前请求的页面“{0}”不存在！", html));
            return File(html, "text/html; charset=utf-8");
        }
    }
}

Yiim.Web/Views/Console/Index.cshtml
<!DOCTYPE html>
<html ng-app="Yiim">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["WebTitle"]</title>
    @Styles.Render("~/js/base/style")
    @Scripts.Render("~/js/base/library")
</head>
<body ng-controller="navigation">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">@ViewData["WebTitle"]</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li class="{{item.isActive?'active':''}}" ng-repeat="item in ls">
                        <a href="#{{item.urls[0].link}}">{{item.name}}</a>
                    </li>
                </ul>
                <div class="navbar-form navbar-right">
                    <a href="@Url.Action("UnLogin", "Console", null)" class="btn btn-danger">
                        {{lang.exit}}
                    </a>
                </div>
            </div>
        </div>
    </nav>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-3 col-md-2 sidebar">
                <ul class="nav nav-sidebar">
                    <li class="{{item.isActive?'active':''}}" ng-repeat="item in urls"><a href="#{{item.link}}">{{item.title}}</a></li>
                </ul>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                <div ng-view></div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/js/angularjs/app")
</body>
</html>